### ISSUE TITLE
Still need the private preview (now public preview could be used) for PowerShell in Mod 04 lab

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-700-Managing-Microsoft-Teams#25]
# Module: 04
#### Steps: 05 & 07

Description of issue
1. In step 5, the current version of MicrosoftTeams PowerShell module is 1.1.4 (As of 7/22/2020) and does not contain the ```-MembershipType``` parameter in ```New-TeamChannel``` cmdlet, so the instruction "if the version is equal to or greater than 1.0.18" is not correct.
1. In step 7, ```-AllowClobber``` needs to be added to the Install-Module command.

**Comment by ITBlandMCT** [comment]
Possible fix:
```
If ((Get-Command New-TeamChannel -ParameterName 'MembershipType' -ErrorAction Ignore) -eq $Null) {"Close PowerShell and install the Teams preview module."} else {"Continue with the current module."}
```

**Comment by ITBlandMCT** [comment]
Update: The **Teams PowerShell public preview** now supports `-MembershipType`. 
Would it be better to use the public preview or continue to show the private preview? (Both solutions work.)
(I vote for public preview-that will require Pull #26 to be updated.)

**Comment by TesterTesterson1004** [comment]
Hate to beat a dead horse, but it appears as if the version that used to be called for here - located in the PsGalleryInt/https://www.poshtestgallery.com/ repository - is now no longer present.  (at least since web 8/12/2020)

I am not sure which version the Course Owner would prefer to specify in instructions going forward, and I believe testing verified ITBlandMCTs comment that the 1.1.4 version on www.powershellgallery.com will not pass the 'MembershipType' test, but at least one potential solution is to use:

**Install-Module -Name MicrosoftTeams -RequiredVersion 1.1.3-preview -AllowPrerelease**

Also, FWIW (at least in the VM I was using to test) in order to get the **-AllowPrerelease** switch to work, I had to also issue command:

**Install-Module PowerShellGet -Force -AllowClobber**

**Comment by ITBlandMCT** [comment]
The current Public Preview version also supports -MembershipType, unless the intent is to show the Private Preview gallery.

All of the newer copies of Teams PowerShell will require -AllowClobber, as they duplicate some of the cmdlets in the Skype for Business PowerShell loaded in the earlier lab.

**Comment by MSFTJenny** [comment]
Thank you for the feedback. I've updated the lab steps.
